// AUTO-GENERATED by _gen-vehicles.mjs — do not edit by hand.
//
// The six vehicles that have their own page on the original. Specs are read out
// of each page rather than retyped, so seat and luggage counts cannot drift.
//
// Note: the original's booking engine carries ten vehicles with different
// capacities (e.g. it quotes the Hiace at 10 passengers where this page says 11).
// These are the marketing pages' numbers, reproduced as published.

export type Vehicle = {
  /** Route segment: /fleet/<slug>. */
  slug: string;
  /** Reference file this page is replicated from. */
  source: string;
  /** The original page's <title>, carried over unchanged. */
  title: string;
  /** <h1> on the vehicle page. */
  name: string;
  tagline: string;
  passengers: number | null;
  largeBags: number | null;
  description: string;
  image: string | null;
};

export const vehicles: Vehicle[] = [
  {
    slug: "toyota-camry",
    source: "toyota-camry.html",
    title: "Toyota Camry",
    name: "Toyota Camry",
    tagline: "The Perfect Blend of Comfort and Reliability.",
    passengers: 3,
    largeBags: 2,
    description: "A globally recognized sedan known for its smooth ride, fuel efficiency, and spacious interior. The Toyota Camry is an excellent choice for business travel, city tours, and airport transfers, offering a dependable and comfortable experience.",
    image: "/uploads/vehicles/1752554098_camry2025-2.png",
  },
  {
    slug: "hyundai-sonata",
    source: "hyundai-sonata.html",
    title: "Hyundai Sonata",
    name: "Hyundai Sonata",
    tagline: "A stylish and modern sedan with a smooth, quiet ride.",
    passengers: 3,
    largeBags: 2,
    description: "The Hyundai Sonata stands out with its bold design and premium features. Offering a quiet, comfortable cabin and the latest technology, it provides a sophisticated travel experience for clients who appreciate style and refinement.",
    image: "/uploads/vehicles/1752554133_sonata2025-2.png",
  },
  {
    slug: "hyundai-staria",
    source: "hyundai-staria.html",
    title: "Hyundai Staria",
    name: "Hyundai Staria",
    tagline: "Futuristic design with unparalleled space and comfort.",
    passengers: 7,
    largeBags: 7,
    description: "The Hyundai Staria redefines group travel with its stunning, futuristic design and lounge-like interior. It offers an exceptionally spacious and luxurious cabin, making it perfect for families and executive groups who desire both style and substance.",
    image: "/uploads/vehicles/1752554248_hyundaistaria2025-2.png",
  },
  {
    slug: "gmc-xl-yukon",
    source: "gmc-xl-yukon.html",
    title: "GMC XL Yukon",
    name: "GMC XL Yukon",
    tagline: "Unmatched luxury and commanding presence.",
    passengers: 7,
    largeBags: 8,
    description: "Experience the pinnacle of SUV luxury with the GMC Yukon XL. Its bold design, premium interior, and powerful performance make it the vehicle of choice for VIPs and those who demand the best. It offers generous space for both passengers and luggage.",
    image: "/uploads/vehicles/1752554276_gmc2025-2.png",
  },
  {
    slug: "hiace-grand-cabin",
    source: "hiace-grand-cabin.html",
    title: "Hiace Grand Cabin",
    name: "Hiace Grand Cabin",
    tagline: "Reliable and spacious for larger group travel.",
    passengers: 11,
    largeBags: 14,
    description: "The Toyota Hiace Grand Cabin is a benchmark for reliability and functionality. It is perfectly suited for transporting larger groups and their luggage comfortably, making it an ideal choice for extended family trips and group Ziyarat tours.",
    image: "/uploads/vehicles/1752554415_Hiace 2025-2.png",
  },
  {
    slug: "coaster",
    source: "coaster.html",
    title: "Coaster / Minibus",
    name: "Coaster / Minibus",
    tagline: "Efficient and comfortable travel for medium-sized groups.",
    passengers: 20,
    largeBags: 25,
    description: "Our Coaster minibuses provide the perfect balance of capacity and maneuverability. They are an excellent choice for tour groups and delegations, offering comfortable seating and ample space for a pleasant and efficient journey.",
    image: "/uploads/vehicles/1752554405_Coaster2025-2.png",
  },
];

export const vehicleBySlug = (slug: string) => vehicles.find((v) => v.slug === slug);
