/**
 * Turns each saved reference page into build input for its route.
 *
 * Produces, per page:
 *   content/<slug>.json      title / description / keywords / body markup
 *   public/page-js/<slug>-N.js   each inline <script>, in document order
 *
 * The body markup is preserved verbatim — same tags, classes, inline styles and
 * order as the original — because that is the only way the result can actually be
 * verified pixel-identical. Two mechanical rewrites are applied:
 *   1. relative asset paths -> absolute (`img/x.png` -> `/img/x.png`), so they
 *      resolve from any route depth;
 *   2. internal page links -> routes (`who-we-are.html` -> `/who-we-are`).
 *
 * Dead links are left pointing where the original points them: `contact.html`
 * and `checkout.html` 404 on the original and will 404 here too.
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Maps each original .html file to its route in the replica. Generated by
 * _gen-data.mjs from data/categories.ts and data/services.ts, so the routes the
 * pages link to and the routes that actually exist can never disagree.
 *
 * A file with no entry keeps the original's own name (`/foo`), which is also
 * what the not-yet-built groups use. `contact.html` and `checkout.html` stay
 * pointed at dead routes on purpose: they 404 on the original too.
 */
const ROUTE_MAP = JSON.parse(await readFile('_route-map.json', 'utf8'));

import { addGuideLinks } from './_chrome.mjs';

const SOFT_404 = /This Page Does Not Exist/i;

const slugOf = (file) => (file === 'index.html' ? 'index' : file.replace(/\.html$/, ''));
const routeOf = (file) =>
  ROUTE_MAP[file] ?? (file === 'index.html' ? '/' : '/' + file.replace(/\.html$/, ''));

/** Absolute-ise the site's own relative asset paths inside an attribute value. */
function fixAssetPath(v) {
  if (/^(https?:|\/\/|data:|mailto:|tel:|#|\/)/i.test(v)) return v;
  if (/^(img|assets|includes|uploads)\//i.test(v)) return '/' + v;
  return v;
}

/** Map an internal .html link to its route. */
function fixLink(v) {
  if (/^(https?:|\/\/|data:|mailto:|tel:|#)/i.test(v)) return v;
  const [path, rest = ''] = v.split(/(?=[?#])/);
  const m = path.match(/^\/?([A-Za-z0-9_-]+\.html)$/);
  if (!m) return fixAssetPath(v);
  const file = m[1];
  const mapped = ROUTE_MAP[file];
  if (mapped) return mapped + rest;
  return (file === 'index.html' ? '/' : '/' + file.replace(/\.html$/, '')) + rest;
}

function rewrite(html) {
  // src / poster on media + scripts, and href on <link> -> absolute assets
  html = html.replace(
    /\b(src|poster)\s*=\s*"([^"]*)"/gi,
    (_, a, v) => `${a}="${fixAssetPath(v)}"`,
  );
  html = html.replace(
    /\bsrcset\s*=\s*"([^"]*)"/gi,
    (_, v) =>
      `srcset="${v
        .split(',')
        .map((part) => {
          const t = part.trim().split(/\s+/);
          t[0] = fixAssetPath(t[0]);
          return t.join(' ');
        })
        .join(', ')}"`,
  );
  // <a href> -> routes; every other href (link/rel) -> absolute asset
  html = html.replace(
    /(<a\b[^>]*?\bhref\s*=\s*)"([^"]*)"/gi,
    (_, pre, v) => `${pre}"${fixLink(v)}"`,
  );
  html = html.replace(
    /(<link\b[^>]*?\bhref\s*=\s*)"([^"]*)"/gi,
    (_, pre, v) => `${pre}"${fixAssetPath(v)}"`,
  );
  // url(...) inside inline styles
  html = html.replace(/url\(\s*'([^']+)'\s*\)/gi, (_, v) => `url('${fixAssetPath(v)}')`);
  html = html.replace(/url\(\s*"([^"]+)"\s*\)/gi, (_, v) => `url("${fixAssetPath(v)}")`);
  return html;
}

const files = (await readdir('_reference')).filter((f) => f.endsWith('.html'));
await mkdir('content', { recursive: true });
await mkdir('public/page-js', { recursive: true });

const index = [];

for (const file of files) {
  const raw = await readFile(join('_reference', file), 'utf8');
  if (SOFT_404.test(raw)) continue; // soft-404s are not real pages

  const slug = slugOf(file);
  const head = raw.slice(0, raw.indexOf('</head>') + 7);

  // Decode entities exactly ONCE. Next re-escapes whatever it is given, so the
  // stored value must be one decode-step away from the original's raw bytes:
  //   original `&amp;`      -> stored `&`      -> emitted `&amp;`
  //   original `&amp;amp;`  -> stored `&amp;`  -> emitted `&amp;amp;`
  // The second case is the original's own double-encoding, reproduced as found.
  const decodeOnce = (t) =>
    t.replace(/&(amp|lt|gt|quot|apos|nbsp|#0?39);/g, (_, e) =>
      ({ amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ', 39: "'", '039': "'" })[e] ?? _,
    );
  const pick = (re) => {
    const m = head.match(re);
    return m ? decodeOnce(m[1].replace(/\s+/g, ' ').trim()) : null;
  };
  const title = pick(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const description =
    pick(/<meta[^>]*name=["']description["'][^>]*content=["']([\s\S]*?)["']/i);
  const keywords = pick(/<meta[^>]*name=["']keywords["'][^>]*content=["']([\s\S]*?)["']/i);

  // Body inner HTML
  const bStart = raw.search(/<body[^>]*>/i);
  const bOpenEnd = raw.indexOf('>', bStart) + 1;
  const bEnd = raw.lastIndexOf('</body>');
  let body = raw.slice(bOpenEnd, bEnd);

  // Pull scripts out of the body: inline ones become files, external ones are
  // recorded so the route can load them in the original order.
  const scripts = [];
  let inlineN = 0;
  body = body.replace(
    /<script\b([^>]*)>([\s\S]*?)<\/script>/gi,
    (whole, attrs, code) => {
      const src = (attrs.match(/src\s*=\s*["']([^"']+)["']/i) || [, null])[1];
      if (src) {
        scripts.push({ type: 'external', src: fixAssetPath(src) });
      } else if (code.trim()) {
        // Name inline scripts by CONTENT hash, not by page. The booking dataset
        // is byte-identical across dozens of pages; hashing means it is written
        // once and the browser caches it across the whole site instead of
        // re-downloading ~128 kB per service page.
        const hash = createHash('sha256').update(code).digest('hex').slice(0, 12);
        const name = `s-${hash}.js`;
        inlineN += 1;
        scripts.push({ type: 'inline', src: `/page-js/${name}`, file: name, code });
      }
      return ''; // removed from markup; re-added as real <script> by the route
    },
  );

  for (const s of scripts) {
    if (s.type === 'inline') {
      await writeFile(join('public/page-js', s.file), s.code, 'utf8');
      delete s.code;
    }
  }

  body = rewrite(body);
  // The single intentional addition to the original's markup: the Ziyarat Guide
  // link, applied to every page so navigation stays consistent sitewide.
  body = addGuideLinks(body);

  await writeFile(
    join('content', `${slug}.json`),
    JSON.stringify({ slug, route: routeOf(file), title, description, keywords, body, scripts }, null, 0),
  );
  index.push({ slug, route: routeOf(file), title, bodyBytes: body.length, scripts: scripts.length });
}

index.sort((a, b) => a.route.localeCompare(b.route, 'en', { numeric: true }));
await writeFile('content/_index.json', JSON.stringify(index, null, 2));

console.log(`pages extracted: ${index.length}`);
const ext = new Set();
for (const p of index) {
  const j = JSON.parse(await readFile(join('content', `${p.slug}.json`), 'utf8'));
  j.scripts.filter((s) => s.type === 'external').forEach((s) => ext.add(s.src));
}
console.log('\ndistinct external scripts referenced across all pages:');
[...ext].sort().forEach((s) => console.log('  ' + s));
