/**
 * Generates data/categories.ts and data/services.ts from the crawl.
 *
 * These typed arrays are the single source of truth for routing: the extractor
 * uses them to rewrite the original's `service_N.html` / `category_N.html` links
 * to the new flat routes, and the dynamic route uses them to know which pages to
 * render. Nothing is hand-written per page.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';

const { categories, services } = JSON.parse(
  await readFile('_reference/_services.json', 'utf8'),
);

const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/\//g, ' ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const meta = async (file) => {
  const h = await readFile(`_reference/${file}`, 'utf8');
  const pick = (re) => {
    const m = h.match(re);
    return m ? m[1].replace(/\s+/g, ' ').trim() : null;
  };
  return {
    title: pick(/<title[^>]*>([\s\S]*?)<\/title>/i),
    description: pick(/<meta[^>]*name=["']description["'][^>]*content=["']([\s\S]*?)["']/i),
    keywords: pick(/<meta[^>]*name=["']keywords["'][^>]*content=["']([\s\S]*?)["']/i),
  };
};

const q = (v) => (v == null ? 'null' : JSON.stringify(v));

/* ---------------------------------------------------------------- categories */
const catRows = [];
for (const [id, c] of Object.entries(categories)) {
  const m = await meta(c.file);
  catRows.push({
    id: Number(id),
    slug: c.slug,
    source: c.file,
    title: m.title,
    serviceIds: c.serviceIds,
  });
}

await mkdir('data', { recursive: true });

await writeFile(
  'data/categories.ts',
  `// AUTO-GENERATED by _gen-data.mjs — do not edit by hand.
// The four service categories, exactly as the original groups them.

export type Category = {
  /** category_N.html on the original. */
  id: number;
  /** Route segment: /services/<slug>. */
  slug: string;
  /** Reference file this page is replicated from. */
  source: string;
  /** The original page's <title>, carried over unchanged. */
  title: string;
  /** Service ids this category page links to, in the original's order. */
  serviceIds: number[];
};

export const categories: Category[] = [
${catRows
  .map(
    (c) =>
      `  { id: ${c.id}, slug: ${q(c.slug)}, source: ${q(c.source)}, title: ${q(c.title)}, serviceIds: [${c.serviceIds.join(', ')}] },`,
  )
  .join('\n')}
];

export const categoryBySlug = (slug: string) => categories.find((c) => c.slug === slug);
`,
);

/* ------------------------------------------------------------------ services */
const svcRows = [];
for (const s of services) {
  const file = `service_${s.id}.html`;
  const m = await meta(file);
  svcRows.push({
    id: s.id,
    slug: slugify(s.title),
    source: file,
    title: m.title,
    categories: s.categories,
  });
}

const dupes = svcRows
  .map((s) => s.slug)
  .filter((s, i, a) => a.indexOf(s) !== i);
if (dupes.length) throw new Error('duplicate service slugs: ' + dupes.join(', '));

await writeFile(
  'data/services.ts',
  `// AUTO-GENERATED by _gen-data.mjs — do not edit by hand.
//
// All 27 service detail pages. Ids are the original's and are not contiguous:
// the sequence runs 1-25, then 30, then 34. Ids 26-29 and 31-33 answer HTTP 200
// with an empty "This Page Does Not Exist" body and are not real pages.
//
// \`categories\` is which category page links to this service on the original.
// Four services are linked from no category at all, and one is linked from two;
// both are reproduced as found rather than corrected.

export type Service = {
  /** service_N.html on the original. */
  id: number;
  /** Route segment: /services/<slug>. */
  slug: string;
  /** Reference file this page is replicated from. */
  source: string;
  /** The original page's <title>, carried over unchanged. */
  title: string;
  /** Slugs of the categories that link here. May be empty, or hold two. */
  categories: string[];
};

export const services: Service[] = [
${svcRows
  .map(
    (s) =>
      `  { id: ${s.id}, slug: ${q(s.slug)}, source: ${q(s.source)}, title: ${q(s.title)}, categories: [${s.categories.map(q).join(', ')}] },`,
  )
  .join('\n')}
];

export const serviceBySlug = (slug: string) => services.find((s) => s.slug === slug);
export const serviceById = (id: number) => services.find((s) => s.id === id);

/** Services a category page lists, in the original's order. */
export const servicesInCategory = (slug: string, ids: number[]) =>
  ids.map((id) => serviceById(id)).filter((s): s is Service => Boolean(s));
`,
);

/* ------------------------------------- route map used by the link rewriter */
const routeMap = {};
for (const c of catRows) routeMap[c.source] = `/services/${c.slug}`;
for (const s of svcRows) routeMap[s.source] = `/services/${s.slug}`;
routeMap['index.html'] = '/';
routeMap['who-we-are.html'] = '/who-we-are';
await writeFile('_route-map.json', JSON.stringify(routeMap, null, 2));

console.log(`categories: ${catRows.length}`);
console.log(`services  : ${svcRows.length}`);
console.log(`route map : ${Object.keys(routeMap).length} entries`);
console.log('\nsample routes:');
for (const k of ['category_1.html', 'category_4.html', 'service_2.html', 'service_34.html'])
  console.log(`  ${k.padEnd(20)} -> ${routeMap[k]}`);
