import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Metadata } from 'next';
import type { PageScript } from '../app/PageScripts';

export type PageContent = {
  slug: string;
  route: string;
  title: string | null;
  description: string | null;
  keywords: string | null;
  /** Body markup, preserved verbatim from the original. */
  body: string;
  scripts: PageScript[];
};

/** Reads one extracted page. Content is generated by `npm run extract`. */
export async function loadPage(slug: string): Promise<PageContent> {
  const raw = await readFile(join(process.cwd(), 'content', `${slug}.json`), 'utf8');
  return JSON.parse(raw) as PageContent;
}

/**
 * Carries the original page's title, description and keywords across unchanged.
 * `title.absolute` is used so Next never appends a template to it — the original
 * titles are exactly what they are.
 */
export function metadataFor(page: PageContent): Metadata {
  return {
    title: { absolute: page.title ?? '' },
    ...(page.description ? { description: page.description } : {}),
    ...(page.keywords ? { keywords: page.keywords } : {}),
  };
}
