// AUTO-GENERATED by _gen-data.mjs — do not edit by hand.
// The four service categories, exactly as the original groups them.

export type Category = {
  /** category_N.html on the original. */
  id: number;
  /** Route segment: /services/<slug>. */
  slug: string;
  /** Reference file this page is replicated from. */
  source: string;
  /** The original page's <title>, carried over unchanged. */
  title: string;
  /** Service ids this category page links to, in the original's order. */
  serviceIds: number[];
};

export const categories: Category[] = [
  { id: 1, slug: "airport-pick-drops", source: "category_1.html", title: "Airport Pick &amp; Drops | AL HARMAIN UMRAH TRANSPORT", serviceIds: [1, 2, 3, 4, 5, 6, 21, 22] },
  { id: 2, slug: "inter-city", source: "category_2.html", title: "Inter-City (City to City) | AL HARMAIN UMRAH TRANSPORT", serviceIds: [8, 9, 10, 11, 12] },
  { id: 3, slug: "local-transfers", source: "category_3.html", title: "Local Transfer | AL HARMAIN UMRAH TRANSPORT", serviceIds: [15, 16, 17, 18, 19] },
  { id: 4, slug: "ziyarat-tours", source: "category_4.html", title: "Ziyarat/Tours | AL HARMAIN UMRAH TRANSPORT", serviceIds: [14, 19, 20, 24, 25, 30] },
];

export const categoryBySlug = (slug: string) => categories.find((c) => c.slug === slug);
