// AUTO-GENERATED by _gen-data.mjs — do not edit by hand.
//
// All 27 service detail pages. Ids are the original's and are not contiguous:
// the sequence runs 1-25, then 30, then 34. Ids 26-29 and 31-33 answer HTTP 200
// with an empty "This Page Does Not Exist" body and are not real pages.
//
// `categories` is which category page links to this service on the original.
// Four services are linked from no category at all, and one is linked from two;
// both are reproduced as found rather than corrected.

export type Service = {
  /** service_N.html on the original. */
  id: number;
  /** Route segment: /services/<slug>. */
  slug: string;
  /** Reference file this page is replicated from. */
  source: string;
  /** The original page's <title>, carried over unchanged. */
  title: string;
  /** Slugs of the categories that link here. May be empty, or hold two. */
  categories: string[];
};

export const services: Service[] = [
  { id: 1, slug: "jeddah-airport-to-jeddah-hotel", source: "service_1.html", title: "Jeddah Airport to Jeddah Hotel", categories: ["airport-pick-drops"] },
  { id: 2, slug: "jeddah-airport-to-makkah-hotel", source: "service_2.html", title: "Jeddah Airport to Makkah Hotel", categories: ["airport-pick-drops"] },
  { id: 3, slug: "jeddah-airport-to-madinah-hotel", source: "service_3.html", title: "Jeddah Airport to Madinah Hotel", categories: ["airport-pick-drops"] },
  { id: 4, slug: "makkah-hotel-to-jeddah-airport", source: "service_4.html", title: "Makkah Hotel to Jeddah Airport", categories: ["airport-pick-drops"] },
  { id: 5, slug: "madinah-hotel-to-jeddah-airport", source: "service_5.html", title: "Madinah Hotel to Jeddah Airport", categories: ["airport-pick-drops"] },
  { id: 6, slug: "jeddah-hotel-to-jeddah-airport", source: "service_6.html", title: "Jeddah Hotel to Jeddah Airport", categories: ["airport-pick-drops"] },
  { id: 7, slug: "jeddah-hotel-to-makkah-hotel", source: "service_7.html", title: "Jeddah Hotel to Makkah Hotel", categories: [] },
  { id: 8, slug: "makkah-hotel-to-jeddah-hotel", source: "service_8.html", title: "Makkah Hotel to Jeddah Hotel", categories: ["inter-city"] },
  { id: 9, slug: "jeddah-hotel-to-madinah-hotel", source: "service_9.html", title: "Jeddah Hotel to Madinah Hotel", categories: ["inter-city"] },
  { id: 10, slug: "madinah-hotel-to-jeddah-hotel", source: "service_10.html", title: "Madinah Hotel to Jeddah Hotel", categories: ["inter-city"] },
  { id: 11, slug: "makkah-hotel-to-madinah-hotel", source: "service_11.html", title: "Makkah Hotel to Madinah Hotel", categories: ["inter-city"] },
  { id: 12, slug: "madinah-hotel-to-makkah-hotel", source: "service_12.html", title: "Madinah Hotel to Makkah Hotel", categories: ["inter-city"] },
  { id: 13, slug: "makkah-hotel-to-madinah-hotel-via-badar-and-roha-well", source: "service_13.html", title: "Makkah Hotel to Madinah Hotel (via Badar &amp;amp; Roha Well)", categories: [] },
  { id: 14, slug: "madinah-hotel-to-makkah-hotel-via-badar-and-roha-well", source: "service_14.html", title: "Madinah Hotel to Makkah Hotel (via Badar &amp;amp; Roha Well)", categories: ["ziyarat-tours"] },
  { id: 15, slug: "makkah-hotel-to-train-station", source: "service_15.html", title: "Makkah Hotel to Train Station", categories: ["local-transfers"] },
  { id: 16, slug: "train-station-to-makkah-hotel", source: "service_16.html", title: "Train Station to Makkah Hotel", categories: ["local-transfers"] },
  { id: 17, slug: "madinah-hotel-to-train-station", source: "service_17.html", title: "Madinah Hotel to Train Station", categories: ["local-transfers"] },
  { id: 18, slug: "train-station-to-madinah-hotel", source: "service_18.html", title: "Train Station to Madinah Hotel", categories: ["local-transfers"] },
  { id: 19, slug: "makkah-ziyarat", source: "service_19.html", title: "Makkah Ziyarat", categories: ["local-transfers", "ziyarat-tours"] },
  { id: 20, slug: "madinah-ziyarat", source: "service_20.html", title: "Madinah Ziyarat", categories: ["ziyarat-tours"] },
  { id: 21, slug: "madinah-airport-to-madinah-hotel", source: "service_21.html", title: "Madinah Airport to Madinah Hotel", categories: ["airport-pick-drops"] },
  { id: 22, slug: "madinah-hotel-to-madinah-airport", source: "service_22.html", title: "Madinah Hotel to Madinah Airport", categories: ["airport-pick-drops"] },
  { id: 23, slug: "makkah-hotel-to-madinah-hotel-via-taif", source: "service_23.html", title: "Makkah Hotel to Madinah Hotel (via Taif)", categories: [] },
  { id: 24, slug: "makkah-to-taif-ziyarat-and-return", source: "service_24.html", title: "Makkah to Taif Ziyarat &amp;amp; Return", categories: ["ziyarat-tours"] },
  { id: 25, slug: "3-in-1-kiswa-factory-makkah-museum-sulah-hudaibiyah", source: "service_25.html", title: "3-in-1 Kiswa Factory / Makkah Museum / Sulah Hudaibiyah", categories: ["ziyarat-tours"] },
  { id: 30, slug: "jeddah-local-city-transfer", source: "service_30.html", title: "Jeddah Local City Transfer", categories: ["ziyarat-tours"] },
  { id: 34, slug: "airport-concierge-and-meet-greet", source: "service_34.html", title: "Airport Concierge &amp;amp; Meet/Greet", categories: [] },
];

export const serviceBySlug = (slug: string) => services.find((s) => s.slug === slug);
export const serviceById = (id: number) => services.find((s) => s.id === id);

/** Services a category page lists, in the original's order. */
export const servicesInCategory = (slug: string, ids: number[]) =>
  ids.map((id) => serviceById(id)).filter((s): s is Service => Boolean(s));
